import type { Tool } from '~/types/tool'

export const useTools = () => {
  const tools: Tool[] = [
    // 🎨 デザイン・UI
    {
      id: 'color-palette',
      name: 'カラーパレット生成',
      description: '美しい配色を自動生成・アクセシビリティチェック',
      category: 'design',
      icon: 'heroicons:swatch',
      route: '/tools/color-palette',
    },
    {
      id: 'gradient-maker',
      name: 'グラデーション作成',
      description: 'CSS/SVGグラデーションをビジュアル作成',
      category: 'design',
      icon: 'heroicons:paint-brush',
      route: '/tools/gradient-maker',
    },
    {
      id: 'shadow-generator',
      name: 'シャドウ生成',
      description: 'box-shadow/text-shadowをリアルタイム調整',
      category: 'design',
      icon: 'heroicons:square-3-stack-3d',
      route: '/tools/shadow-generator',
    },
    {
      id: 'flexbox-playground',
      name: 'Flexbox プレイグラウンド',
      description: 'Flexboxレイアウトをインタラクティブ学習',
      category: 'design',
      icon: 'heroicons:view-columns',
      route: '/tools/flexbox-playground',
    },
    {
      id: 'grid-generator',
      name: 'CSS Grid 生成',
      description: 'グリッドレイアウトをビジュアル作成',
      category: 'design',
      icon: 'heroicons:squares-2x2',
      route: '/tools/grid-generator',
    },

    // 🖼️ 画像・メディア
    {
      id: 'image-format-converter',
      name: '画像編集ツール',
      description: 'フォーマット変換・リサイズ・フィルター一括処理',
      category: 'image',
      icon: 'heroicons:photo',
      route: '/tools/image-format-converter',
    },
    {
      id: 'image-compressor',
      name: '画像圧縮・最適化',
      description: 'ファイルサイズを削減して読み込み高速化',
      category: 'image',
      icon: 'heroicons:archive-box-arrow-down',
      route: '/tools/image-compressor',
    },
    {
      id: 'image-compare',
      name: '画像比較・差分確認',
      description: '2つの画像を並べて詳細比較',
      category: 'image',
      icon: 'heroicons:eye',
      route: '/tools/image-compare',
    },
    {
      id: 'image-metadata-viewer',
      name: '画像メタデータ確認',
      description: 'Exif情報表示・プライバシー保護削除',
      category: 'image',
      icon: 'heroicons:information-circle',
      route: '/tools/image-metadata-viewer',
    },
    {
      id: 'sprite-sheet-generator',
      name: 'スプライトシート作成',
      description: '複数画像を1つにまとめてCSS生成',
      category: 'image',
      icon: 'heroicons:squares-plus',
      route: '/tools/sprite-sheet-generator',
    },
    {
      id: 'favicon-generator',
      name: 'ファビコン生成',
      description: '各種サイズのファビコンを一括作成',
      category: 'image',
      icon: 'heroicons:star',
      route: '/tools/favicon-generator',
    },
    {
      id: 'color-palette-extractor',
      name: 'カラーパレット抽出',
      description: '画像から主要色を自動抽出',
      category: 'image',
      icon: 'heroicons:eye-dropper',
      route: '/tools/color-palette-extractor',
    },
    {
      id: 'base64-image',
      name: 'Base64画像変換',
      description: '画像をBase64データURIに変換',
      category: 'image',
      icon: 'heroicons:photo',
      route: '/tools/base64-image',
    },
    {
      id: 'webp-avif-converter',
      name: 'WebP/AVIF変換',
      description: '次世代画像フォーマットへの一括変換',
      category: 'image',
      icon: 'heroicons:arrow-path',
      route: '/tools/webp-avif-converter',
      badge: 'New',
    },
    {
      id: 'svg-optimizer',
      name: 'SVG最適化',
      description: 'SVGファイルを最適化してサイズ削減',
      category: 'image',
      icon: 'heroicons:sparkles',
      route: '/tools/svg-optimizer',
      badge: 'New',
    },
    {
      id: 'ai-background-remover',
      name: 'AI背景除去',
      description: 'ブラウザ上で画像の背景を自動検出・除去',
      category: 'image',
      icon: 'heroicons:scissors',
      route: '/tools/ai-background-remover',
      badge: 'New',
    },
    {
      id: 'blur-generator',
      name: 'ブラー生成',
      description: 'プレースホルダー用のブラー画像生成',
      category: 'image',
      icon: 'heroicons:sparkles',
      route: '/tools/blur-generator',
      badge: 'New',
    },
    {
      id: 'ascii-art-converter',
      name: 'アスキーアート変換',
      description: '画像をテキストアートに変換',
      category: 'image',
      icon: 'heroicons:code-bracket',
      route: '/tools/ascii-art-converter',
      badge: 'New',
    },
    {
      id: 'video-editor',
      name: '動画編集・圧縮',
      description: '2分以内の動画トリミング・圧縮',
      category: 'image',
      icon: 'heroicons:video-camera',
      route: '/tools/video-editor',
    },

    // 📝 テキスト・文書
    {
      id: 'lorem-ipsum',
      name: 'ダミーテキスト生成',
      description: '日本語・英語対応のLorem Ipsum作成',
      category: 'text',
      icon: 'heroicons:document-duplicate',
      route: '/tools/lorem-ipsum',
    },
    {
      id: 'text-encryptor',
      name: 'テキスト暗号化',
      description: 'AES暗号化でテキストを安全に保護',
      category: 'text',
      icon: 'heroicons:shield-check',
      route: '/tools/text-encryptor',
      badge: 'New',
    },
    {
      id: 'character-counter',
      name: '文字数・バイト数計測',
      description: '文字数・バイト数・行数をリアルタイム集計',
      category: 'text',
      icon: 'heroicons:calculator',
      route: '/tools/character-counter',
    },
    {
      id: 'regex-tester',
      name: '正規表現テスター',
      description: 'パターンマッチをリアルタイム検証',
      category: 'text',
      icon: 'heroicons:magnifying-glass',
      route: '/tools/regex-tester',
    },
    {
      id: 'diff-viewer',
      name: 'テキスト差分比較',
      description: '2つのテキストの違いを視覚的に表示',
      category: 'text',
      icon: 'heroicons:document-minus',
      route: '/tools/diff-viewer',
    },
    {
      id: 'character-encoding-converter',
      name: '文字コード変換',
      description: 'エンコーディング変換・文字化け修復',
      category: 'text',
      icon: 'heroicons:language',
      route: '/tools/character-encoding-converter',
      badge: 'New',
    },
    {
      id: 'text-proofreader',
      name: '文章校正',
      description: '誤字脱字・表記ゆれを自動チェック',
      category: 'text',
      icon: 'heroicons:document-magnifying-glass',
      route: '/tools/text-proofreader',
      badge: 'New',
    },
    {
      id: 'text-replacer',
      name: 'テキスト置換',
      description: '一括置換・正規表現対応',
      category: 'text',
      icon: 'heroicons:magnifying-glass-plus',
      route: '/tools/text-replacer',
      badge: 'New',
    },

    // 🔄 変換・コンバーター
    {
      id: 'csv-json-converter',
      name: 'CSV ↔ JSON 変換',
      description: 'CSVとJSONの双方向データ変換',
      category: 'converter',
      icon: 'heroicons:arrow-path-rounded-square',
      route: '/tools/csv-json-converter',
    },
    {
      id: 'markdown-to-html',
      name: 'Markdown → HTML',
      description: 'Markdownをリアルタイム変換・プレビュー',
      category: 'converter',
      icon: 'heroicons:document-text',
      route: '/tools/markdown-to-html',
    },
    {
      id: 'json-to-typescript',
      name: 'JSON → TypeScript型',
      description: 'JSONから型定義を自動生成',
      category: 'converter',
      icon: 'heroicons:code-bracket',
      route: '/tools/json-to-typescript',
    },
    {
      id: 'base64-encoder',
      name: 'Base64 エンコード',
      description: 'テキストをBase64形式に相互変換',
      category: 'converter',
      icon: 'heroicons:arrows-right-left',
      route: '/tools/base64-encoder',
    },
    {
      id: 'base64-file-encoder',
      name: 'Base64ファイル変換',
      description: 'ファイル専用Base64エンコーダー',
      category: 'converter',
      icon: 'heroicons:document-arrow-up',
      route: '/tools/base64-file-encoder',
      badge: 'New',
    },
    {
      id: 'url-encoder',
      name: 'URL エンコード',
      description: 'URLパラメータの文字列変換',
      category: 'converter',
      icon: 'heroicons:link',
      route: '/tools/url-encoder',
    },
    {
      id: 'timestamp-converter',
      name: 'タイムスタンプ変換',
      description: 'Unix時間と日時の相互変換',
      category: 'converter',
      icon: 'heroicons:clock',
      route: '/tools/timestamp-converter',
    },
    {
      id: 'epoch-time-calculator',
      name: 'エポック時間計算機',
      description: '日時差分・タイムゾーン変換・期間計算',
      category: 'converter',
      icon: 'heroicons:calendar-days',
      route: '/tools/epoch-time-calculator',
      badge: 'New',
    },
    {
      id: 'unit-converter',
      name: '単位変換',
      description: '長さ・重さ・温度・CSS単位など相互変換',
      category: 'converter',
      icon: 'heroicons:arrows-right-left',
      route: '/tools/unit-converter',
      badge: 'New',
    },

    // ⚡ 開発・セキュリティ
    {
      id: 'json-formatter',
      name: 'JSON 整形・検証',
      description: 'JSONの構文チェックと美化',
      category: 'dev',
      icon: 'heroicons:code-bracket-square',
      route: '/tools/json-formatter',
    },
    {
      id: 'jsonpath-tester',
      name: 'JSONPathテスター',
      description: 'JSONデータの抽出・フィルタリング',
      category: 'dev',
      icon: 'heroicons:funnel',
      route: '/tools/jsonpath-tester',
      badge: 'New',
    },
    {
      id: 'jwt-decoder',
      name: 'JWT 解析・検証',
      description: 'JWTトークンのデコードと署名確認',
      category: 'dev',
      icon: 'heroicons:key',
      route: '/tools/jwt-decoder',
    },
    {
      id: 'uuid-generator',
      name: 'UUID・ID生成',
      description: '各種形式のユニークID作成',
      category: 'dev',
      icon: 'heroicons:hashtag',
      route: '/tools/uuid-generator',
    },
    {
      id: 'password-generator',
      name: 'パスワード生成',
      description: 'セキュアで強力なパスワード作成',
      category: 'dev',
      icon: 'heroicons:lock-closed',
      route: '/tools/password-generator',
    },
    {
      id: 'qr-code-generator',
      name: 'QRコード生成',
      description: 'テキスト・URLからQRコード作成',
      category: 'dev',
      icon: 'heroicons:qr-code',
      route: '/tools/qr-code-generator',
    },
    {
      id: 'cron-expression-builder',
      name: 'Cron式ビルダー',
      description: 'スケジュール実行設定を視覚的作成',
      category: 'dev',
      icon: 'heroicons:cog-6-tooth',
      route: '/tools/cron-expression-builder',
    },
    {
      id: 'hash-generator',
      name: 'ハッシュ生成',
      description: 'MD5/SHA256/SHA512等のハッシュ値生成',
      category: 'dev',
      icon: 'heroicons:finger-print',
      route: '/tools/hash-generator',
      badge: 'New',
    },
    {
      id: 'og-tag-generator',
      name: 'OGタグ生成',
      description: 'SNS共有用メタタグ生成',
      category: 'dev',
      icon: 'heroicons:share',
      route: '/tools/og-tag-generator',
      badge: 'New',
    },
    {
      id: 'gitignore-generator',
      name: '.gitignore生成',
      description: '言語別テンプレート生成',
      category: 'dev',
      icon: 'heroicons:document-minus',
      route: '/tools/gitignore-generator',
      badge: 'New',
    },

    // 🔄 変換・コンバーター（追加）
    {
      id: 'yaml-json-converter',
      name: 'YAML ↔ JSON変換',
      description: 'YAMLとJSONの相互変換',
      category: 'converter',
      icon: 'heroicons:arrows-right-left',
      route: '/tools/yaml-json-converter',
      badge: 'New',
    },

    // 🎨 デザイン・UI（追加）
    {
      id: 'color-contrast-checker',
      name: 'カラーコントラストチェッカー',
      description: 'WCAG準拠のアクセシビリティチェック',
      category: 'design',
      icon: 'heroicons:eye',
      route: '/tools/color-contrast-checker',
      badge: 'New',
    },
    {
      id: 'color-code-converter',
      name: 'カラーコード変換',
      description: 'HEX/RGB/HSL/HSV/CMYK相互変換・色理論パレット生成',
      category: 'design',
      icon: 'heroicons:beaker',
      route: '/tools/color-code-converter',
      badge: 'New',
    },
    {
      id: 'animation-generator',
      name: 'アニメーション生成',
      description: 'CSS/SVGアニメーションを視覚的に作成',
      category: 'design',
      icon: 'heroicons:play-circle',
      route: '/tools/animation-generator',
      badge: 'New',
    },
    {
      id: 'font-pairing',
      name: 'フォントペアリング',
      description: '相性の良いフォントの組み合わせを提案',
      category: 'design',
      icon: 'heroicons:document-text',
      route: '/tools/font-pairing',
      badge: 'New',
    },

    // 📝 テキスト・文書（追加）
    {
      id: 'markdown-table-generator',
      name: 'Markdownテーブル生成',
      description: 'GUIでMarkdownテーブルを作成',
      category: 'text',
      icon: 'heroicons:table-cells',
      route: '/tools/markdown-table-generator',
      badge: 'New',
    },

    // 🧮 計算・数学
    {
      id: 'number-base-converter',
      name: '進数変換計算機',
      description: '2進数/8進数/10進数/16進数の相互変換',
      category: 'math',
      icon: 'heroicons:calculator',
      route: '/tools/number-base-converter',
      badge: 'New',
    },
  ]

  const getToolsByCategory = (category: Tool['category']) => {
    return tools.filter(tool => tool.category === category)
  }

  const getToolById = (id: string) => {
    return tools.find(tool => tool.id === id)
  }

  return {
    tools,
    getToolsByCategory,
    getToolById,
  }
}
