<script setup lang="ts">
import { ref, watch } from 'vue'
import { useClipboard } from '@vueuse/core'

definePageMeta({
  layout: 'tools',
})

// 状態管理
const selectedLanguages = ref<string[]>([])
const selectedFrameworks = ref<string[]>([])
const selectedIDEs = ref<string[]>([])
const selectedOS = ref<string[]>([])
const customRules = ref('')
const includeComments = ref(true)
const generatedGitignore = ref('')

// テンプレートデータ
const templates = {
  languages: [
    {
      id: 'node',
      name: 'Node.js',
      icon: 'logos:nodejs-icon',
      rules: `# Dependencies
node_modules/
.npm/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-store/

# Testing
coverage/
.nyc_output/

# Production
build/
dist/

# Misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
logs/
*.log

# Runtime data
pids/
*.pid
*.seed
*.pid.lock`,
    },
    {
      id: 'python',
      name: 'Python',
      icon: 'logos:python',
      rules: `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
*.manifest
*.spec

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/
.pytest_cache/

# Virtual environments
venv/
ENV/
env/
.venv

# Jupyter Notebook
.ipynb_checkpoints

# pyenv
.python-version

# Environments
.env
.venv`,
    },
    {
      id: 'java',
      name: 'Java',
      icon: 'logos:java',
      rules: `# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs
hs_err_pid*
replay_pid*`,
    },
    {
      id: 'go',
      name: 'Go',
      icon: 'logos:go',
      rules: `# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with \`go test -c\`
*.test

# Output of the go coverage tool
*.out

# Dependency directories
vendor/

# Go workspace file
go.work`,
    },
    {
      id: 'rust',
      name: 'Rust',
      icon: 'logos:rust',
      rules: `# Generated by Cargo
/target/
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these
*.pdb`,
    },
    {
      id: 'csharp',
      name: 'C#',
      icon: 'logos:c-sharp',
      rules: `# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Ww][Ii][Nn]32/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/

# Visual Studio cache/options directory
.vs/

# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/

# Files built by Visual Studio
*.pdb
*.ilk
*.meta
*.obj
*.iobj
*.pch
*.ipdb
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.tmp_proj
*_i.c
*_p.c
*_h.h
*.idb
*.opensdf
*.sdf
*.cachefile
*.VC.db
*.VC.VC.opendb`,
    },
  ],
  frameworks: [
    {
      id: 'react',
      name: 'React',
      icon: 'logos:react',
      rules: `# React / Next.js
.next/
out/
.cache/
*.tsbuildinfo
next-env.d.ts`,
    },
    {
      id: 'vue',
      name: 'Vue',
      icon: 'logos:vue',
      rules: `# Vue / Nuxt
.nuxt/
.nitro/
.cache/
.output/
dist/
.vite-inspect/`,
    },
    {
      id: 'angular',
      name: 'Angular',
      icon: 'logos:angular-icon',
      rules: `# Angular
.angular/
tmp/
out-tsc/
bazel-out/`,
    },
    {
      id: 'django',
      name: 'Django',
      icon: 'logos:django-icon',
      rules: `# Django
*.pyc
__pycache__/
db.sqlite3
db.sqlite3-journal
media/
staticfiles/

# Django migrations
*/migrations/*.py
!*/migrations/__init__.py`,
    },
    {
      id: 'rails',
      name: 'Ruby on Rails',
      icon: 'logos:rails',
      rules: `# Rails
/.bundle
/db/*.sqlite3
/db/*.sqlite3-journal
/db/*.sqlite3-*
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep
/storage/*
!/storage/.keep
/public/assets
.byebug_history
/config/master.key
/public/packs
/public/packs-test
/node_modules
/yarn-error.log
yarn-debug.log*
.yarn-integrity`,
    },
    {
      id: 'laravel',
      name: 'Laravel',
      icon: 'logos:laravel',
      rules: `# Laravel
/vendor/
node_modules/
npm-debug.log
yarn-error.log
.env
.env.backup
.phpunit.result.cache
Homestead.json
Homestead.yaml
auth.json
/public/hot
/public/storage
/storage/*.key`,
    },
  ],
  ides: [
    {
      id: 'vscode',
      name: 'VS Code',
      icon: 'logos:visual-studio-code',
      rules: `# VS Code
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets
.history/
*.vsix`,
    },
    {
      id: 'jetbrains',
      name: 'JetBrains',
      icon: 'logos:jetbrains',
      rules: `# JetBrains IDEs
.idea/
*.iml
*.iws
*.ipr
out/
.idea_modules/`,
    },
    {
      id: 'vim',
      name: 'Vim',
      icon: 'logos:vim',
      rules: `# Vim
[._]*.s[a-v][a-z]
!*.svg
[._]*.sw[a-p]
[._]s[a-rt-v][a-z]
[._]ss[a-gi-z]
[._]sw[a-p]
Session.vim
Sessionx.vim
.netrwhist
*~
tags
[._]*.un~`,
    },
    {
      id: 'sublime',
      name: 'Sublime Text',
      icon: 'logos:sublime-text',
      rules: `# Sublime Text
*.tmlanguage.cache
*.tmPreferences.cache
*.stTheme.cache
*.sublime-workspace
*.sublime-project
sftp-config.json
sftp-config-alt*.json
Package Control.last-run
Package Control.ca-list
Package Control.ca-bundle
Package Control.system-ca-bundle
Package Control.cache/
Package Control.ca-certs/
Package Control.merged-ca-bundle
Package Control.user-ca-bundle
oscrypto-ca-bundle.crt
bh_unicode_properties.cache
GitHub.sublime-settings`,
    },
  ],
  os: [
    {
      id: 'macos',
      name: 'macOS',
      icon: 'logos:apple',
      rules: `# macOS
.DS_Store
.AppleDouble
.LSOverride
Icon
._*
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk`,
    },
    {
      id: 'windows',
      name: 'Windows',
      icon: 'logos:microsoft-windows',
      rules: `# Windows
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db
*.stackdump
[Dd]esktop.ini
$RECYCLE.BIN/
*.cab
*.msi
*.msix
*.msm
*.msp
*.lnk`,
    },
    {
      id: 'linux',
      name: 'Linux',
      icon: 'logos:linux-tux',
      rules: `# Linux
*~
.fuse_hidden*
.directory
.Trash-*
.nfs*`,
    },
  ],
}

// 一般的なルール
const commonRules = `# General
*.log
*.tmp
*.temp
*.cache
*.bak
*.swp
*.swo
*~

# Environment variables
.env
.env.*
!.env.example

# IDEs and editors
.vscode/
.idea/
*.sublime-project
*.sublime-workspace

# OS generated files
.DS_Store
Thumbs.db

# Compiled output
dist/
build/
out/
*.out

# Dependencies
node_modules/
vendor/
bower_components/

# Testing
coverage/
.nyc_output/

# Temporary files
tmp/
temp/
.tmp/
.temp/`

// 人気の組み合わせ
const popularCombinations = [
  {
    name: 'MERN Stack',
    languages: ['node'],
    frameworks: ['react'],
    ides: ['vscode'],
    os: ['macos', 'windows'],
  },
  {
    name: 'Vue + TypeScript',
    languages: ['node'],
    frameworks: ['vue'],
    ides: ['vscode'],
    os: ['macos', 'windows'],
  },
  {
    name: 'Python Web',
    languages: ['python'],
    frameworks: ['django'],
    ides: ['vscode', 'jetbrains'],
    os: ['macos', 'linux'],
  },
  {
    name: 'Java Spring',
    languages: ['java'],
    frameworks: [],
    ides: ['jetbrains'],
    os: ['windows', 'linux'],
  },
]

// .gitignore生成
const generateGitignore = () => {
  const sections: string[] = []

  // ヘッダー
  if (includeComments.value) {
    sections.push(`# Generated by gitignore generator
# https://example.com/tools/gitignore-generator
# Created: ${new Date().toISOString()}`)
    sections.push('')
  }

  // 共通ルール
  if (includeComments.value) {
    sections.push('# ==================== General ====================')
  }
  sections.push(commonRules)
  sections.push('')

  // 言語固有のルール
  if (selectedLanguages.value.length > 0) {
    if (includeComments.value) {
      sections.push('# ==================== Languages ====================')
    }
    selectedLanguages.value.forEach((langId) => {
      const lang = templates.languages.find(l => l.id === langId)
      if (lang) {
        if (includeComments.value) {
          sections.push(`# ${lang.name}`)
        }
        sections.push(lang.rules)
        sections.push('')
      }
    })
  }

  // フレームワーク固有のルール
  if (selectedFrameworks.value.length > 0) {
    if (includeComments.value) {
      sections.push('# ==================== Frameworks ====================')
    }
    selectedFrameworks.value.forEach((fwId) => {
      const fw = templates.frameworks.find(f => f.id === fwId)
      if (fw) {
        if (includeComments.value) {
          sections.push(`# ${fw.name}`)
        }
        sections.push(fw.rules)
        sections.push('')
      }
    })
  }

  // IDE固有のルール
  if (selectedIDEs.value.length > 0) {
    if (includeComments.value) {
      sections.push('# ==================== IDEs ====================')
    }
    selectedIDEs.value.forEach((ideId) => {
      const ide = templates.ides.find(i => i.id === ideId)
      if (ide) {
        if (includeComments.value) {
          sections.push(`# ${ide.name}`)
        }
        sections.push(ide.rules)
        sections.push('')
      }
    })
  }

  // OS固有のルール
  if (selectedOS.value.length > 0) {
    if (includeComments.value) {
      sections.push('# ==================== Operating Systems ====================')
    }
    selectedOS.value.forEach((osId) => {
      const os = templates.os.find(o => o.id === osId)
      if (os) {
        if (includeComments.value) {
          sections.push(`# ${os.name}`)
        }
        sections.push(os.rules)
        sections.push('')
      }
    })
  }

  // カスタムルール
  if (customRules.value.trim()) {
    if (includeComments.value) {
      sections.push('# ==================== Custom Rules ====================')
    }
    sections.push(customRules.value.trim())
    sections.push('')
  }

  generatedGitignore.value = sections.join('\n').trim()
}

// 選択変更時に自動生成
watch([selectedLanguages, selectedFrameworks, selectedIDEs, selectedOS, customRules, includeComments], () => {
  generateGitignore()
}, { deep: true })

// 人気の組み合わせを適用
const applyPopularCombination = (combination: typeof popularCombinations[0]) => {
  selectedLanguages.value = [...combination.languages]
  selectedFrameworks.value = [...combination.frameworks]
  selectedIDEs.value = [...combination.ides]
  selectedOS.value = [...combination.os]

  toast({
    title: '組み合わせを適用',
    description: `「${combination.name}」の設定を適用しました`,
  })
}

// 全選択/全解除
const selectAll = (category: 'languages' | 'frameworks' | 'ides' | 'os') => {
  switch (category) {
    case 'languages':
      selectedLanguages.value = templates.languages.map(l => l.id)
      break
    case 'frameworks':
      selectedFrameworks.value = templates.frameworks.map(f => f.id)
      break
    case 'ides':
      selectedIDEs.value = templates.ides.map(i => i.id)
      break
    case 'os':
      selectedOS.value = templates.os.map(o => o.id)
      break
  }
}

const deselectAll = (category: 'languages' | 'frameworks' | 'ides' | 'os') => {
  switch (category) {
    case 'languages':
      selectedLanguages.value = []
      break
    case 'frameworks':
      selectedFrameworks.value = []
      break
    case 'ides':
      selectedIDEs.value = []
      break
    case 'os':
      selectedOS.value = []
      break
  }
}

// リセット
const reset = () => {
  selectedLanguages.value = []
  selectedFrameworks.value = []
  selectedIDEs.value = []
  selectedOS.value = []
  customRules.value = ''
  generatedGitignore.value = ''
}

// クリップボード操作
const { copy } = useClipboard()
const { toast } = useToast()

const copyToClipboard = async () => {
  try {
    await copy(generatedGitignore.value)
    toast({
      description: 'クリップボードにコピーしました',
    })
  }
  catch (err) {
    console.error('Failed to copy:', err)
    toast({
      description: 'コピーに失敗しました',
      variant: 'destructive',
    })
  }
}

// ダウンロード
const downloadGitignore = () => {
  const blob = new Blob([generatedGitignore.value], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')

  link.href = url
  link.download = '.gitignore'
  link.click()

  URL.revokeObjectURL(url)
}

// 初期生成
onMounted(() => {
  generateGitignore()
})

// SEO設定
useSeoMeta({
  title: '.gitignore生成 | Web開発ツール',
  description: '言語・フレームワーク別の.gitignoreテンプレート生成。カスタマイズ可能。',
})
</script>

<template>
  <div class="space-y-6">
    <div>
      <h1 class="text-3xl font-bold mb-2">
        .gitignore生成
      </h1>
      <p class="text-muted-foreground">
        プロジェクトに最適な.gitignoreファイルを生成します。
      </p>
    </div>

    <!-- 人気の組み合わせ -->
    <Card>
      <CardHeader>
        <CardTitle>人気の組み合わせ</CardTitle>
      </CardHeader>
      <CardContent>
        <div class="flex flex-wrap gap-2">
          <Button
            v-for="combo in popularCombinations"
            :key="combo.name"
            variant="outline"
            size="sm"
            @click="applyPopularCombination(combo)">
            {{ combo.name }}
          </Button>
          <Button
            variant="ghost"
            size="sm"
            @click="reset">
            リセット
          </Button>
        </div>
      </CardContent>
    </Card>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <!-- 選択エリア -->
      <div class="space-y-6">
        <!-- 言語 -->
        <Card>
          <CardHeader>
            <div class="flex items-center justify-between">
              <CardTitle>プログラミング言語</CardTitle>
              <div class="flex gap-1">
                <Button
                  variant="ghost"
                  size="sm"
                  @click="selectAll('languages')">
                  全選択
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  @click="deselectAll('languages')">
                  解除
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div class="grid grid-cols-2 gap-3">
              <label
                v-for="lang in templates.languages"
                :key="lang.id"
                class="flex items-center gap-2 cursor-pointer hover:bg-muted p-2 rounded">
                <input
                  v-model="selectedLanguages"
                  :value="lang.id"
                  type="checkbox"
                  class="w-4 h-4 rounded border-zinc-300 text-primary focus:ring-primary focus:ring-offset-0">
                <Icon :name="lang.icon" class="w-5 h-5" />
                <span class="text-sm">{{ lang.name }}</span>
              </label>
            </div>
          </CardContent>
        </Card>

        <!-- フレームワーク -->
        <Card>
          <CardHeader>
            <div class="flex items-center justify-between">
              <CardTitle>フレームワーク</CardTitle>
              <div class="flex gap-1">
                <Button
                  variant="ghost"
                  size="sm"
                  @click="selectAll('frameworks')">
                  全選択
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  @click="deselectAll('frameworks')">
                  解除
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div class="grid grid-cols-2 gap-3">
              <label
                v-for="fw in templates.frameworks"
                :key="fw.id"
                class="flex items-center gap-2 cursor-pointer hover:bg-muted p-2 rounded">
                <input
                  v-model="selectedFrameworks"
                  :value="fw.id"
                  type="checkbox"
                  class="w-4 h-4 rounded border-zinc-300 text-primary focus:ring-primary focus:ring-offset-0">
                <Icon :name="fw.icon" class="w-5 h-5" />
                <span class="text-sm">{{ fw.name }}</span>
              </label>
            </div>
          </CardContent>
        </Card>

        <!-- IDE -->
        <Card>
          <CardHeader>
            <div class="flex items-center justify-between">
              <CardTitle>IDE / エディタ</CardTitle>
              <div class="flex gap-1">
                <Button
                  variant="ghost"
                  size="sm"
                  @click="selectAll('ides')">
                  全選択
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  @click="deselectAll('ides')">
                  解除
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div class="grid grid-cols-2 gap-3">
              <label
                v-for="ide in templates.ides"
                :key="ide.id"
                class="flex items-center gap-2 cursor-pointer hover:bg-muted p-2 rounded">
                <input
                  v-model="selectedIDEs"
                  :value="ide.id"
                  type="checkbox"
                  class="w-4 h-4 rounded border-zinc-300 text-primary focus:ring-primary focus:ring-offset-0">
                <Icon :name="ide.icon" class="w-5 h-5" />
                <span class="text-sm">{{ ide.name }}</span>
              </label>
            </div>
          </CardContent>
        </Card>

        <!-- OS -->
        <Card>
          <CardHeader>
            <div class="flex items-center justify-between">
              <CardTitle>OS</CardTitle>
              <div class="flex gap-1">
                <Button
                  variant="ghost"
                  size="sm"
                  @click="selectAll('os')">
                  全選択
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  @click="deselectAll('os')">
                  解除
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div class="grid grid-cols-2 gap-3">
              <label
                v-for="os in templates.os"
                :key="os.id"
                class="flex items-center gap-2 cursor-pointer hover:bg-muted p-2 rounded">
                <input
                  v-model="selectedOS"
                  :value="os.id"
                  type="checkbox"
                  class="w-4 h-4 rounded border-zinc-300 text-primary focus:ring-primary focus:ring-offset-0">
                <Icon :name="os.icon" class="w-5 h-5" />
                <span class="text-sm">{{ os.name }}</span>
              </label>
            </div>
          </CardContent>
        </Card>

        <!-- カスタムルール -->
        <Card>
          <CardHeader>
            <CardTitle>カスタムルール</CardTitle>
          </CardHeader>
          <CardContent>
            <textarea
              v-model="customRules"
              placeholder="# 追加したいルールを入力&#10;*.custom&#10;special-folder/"
              class="w-full h-32 p-3 font-mono text-sm border rounded-md bg-background resize-none"
              spellcheck="false"></textarea>
          </CardContent>
        </Card>

        <!-- オプション -->
        <Card>
          <CardHeader>
            <CardTitle>オプション</CardTitle>
          </CardHeader>
          <CardContent>
            <label class="flex items-center gap-2">
              <input
                v-model="includeComments"
                type="checkbox"
                class="w-4 h-4 rounded border-zinc-300 text-primary focus:ring-primary focus:ring-offset-0">
              <span class="text-sm">コメントを含める</span>
            </label>
          </CardContent>
        </Card>
      </div>

      <!-- 出力エリア -->
      <div class="space-y-6">
        <!-- 統計情報 -->
        <Card>
          <CardHeader>
            <CardTitle>選択内容</CardTitle>
          </CardHeader>
          <CardContent>
            <div class="space-y-2 text-sm">
              <div v-if="selectedLanguages.length > 0">
                <span class="text-muted-foreground">言語:</span>
                <span class="ml-2">
                  {{ selectedLanguages.map(id => templates.languages.find(l => l.id === id)?.name).filter(Boolean).join(', ') }}
                </span>
              </div>
              <div v-if="selectedFrameworks.length > 0">
                <span class="text-muted-foreground">フレームワーク:</span>
                <span class="ml-2">
                  {{ selectedFrameworks.map(id => templates.frameworks.find(f => f.id === id)?.name).filter(Boolean).join(', ') }}
                </span>
              </div>
              <div v-if="selectedIDEs.length > 0">
                <span class="text-muted-foreground">IDE:</span>
                <span class="ml-2">
                  {{ selectedIDEs.map(id => templates.ides.find(i => i.id === id)?.name).filter(Boolean).join(', ') }}
                </span>
              </div>
              <div v-if="selectedOS.length > 0">
                <span class="text-muted-foreground">OS:</span>
                <span class="ml-2">
                  {{ selectedOS.map(id => templates.os.find(o => o.id === id)?.name).filter(Boolean).join(', ') }}
                </span>
              </div>
              <div v-if="!selectedLanguages.length && !selectedFrameworks.length && !selectedIDEs.length && !selectedOS.length">
                <span class="text-muted-foreground">選択されていません</span>
              </div>
            </div>
          </CardContent>
        </Card>

        <!-- 生成された.gitignore -->
        <Card>
          <CardHeader>
            <div class="flex items-center justify-between">
              <CardTitle>.gitignore</CardTitle>
              <div class="flex gap-2">
                <Button
                  size="sm"
                  variant="ghost"
                  @click="copyToClipboard">
                  <Icon name="heroicons:clipboard-document" class="w-4 h-4" />
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  @click="downloadGitignore">
                  <Icon name="heroicons:arrow-down-tray" class="w-4 h-4" />
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <textarea
              v-model="generatedGitignore"
              readonly
              class="w-full h-96 p-3 font-mono text-sm border rounded-md bg-muted resize-none"
              spellcheck="false"></textarea>
            <div class="mt-2 text-sm text-muted-foreground">
              {{ generatedGitignore.split('\n').length }}行 / {{ generatedGitignore.length }}文字
            </div>
          </CardContent>
        </Card>

        <!-- 使い方 -->
        <Alert>
          <Icon name="heroicons:information-circle" class="w-4 h-4" />
          <AlertTitle>使い方</AlertTitle>
          <AlertDescription>
            <ol class="list-decimal list-inside mt-2 space-y-1">
              <li>使用する言語、フレームワーク、IDE、OSを選択</li>
              <li>必要に応じてカスタムルールを追加</li>
              <li>生成された内容をコピーまたはダウンロード</li>
              <li>プロジェクトルートに.gitignoreファイルとして保存</li>
            </ol>
          </AlertDescription>
        </Alert>
      </div>
    </div>
  </div>
</template>
